#===============================================================================
# Copyright (C) 2011 Diego Duclos
#
# This file is part of Eos.
#
# Eos is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Eos is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Eos. If not, see <http://www.gnu.org/licenses/>.
#===============================================================================

import collections

from eos import const

class ExpressionInfo(object):
    """
    The ExpressionInfo objects are the actual "Core" of eos,
    they are what eventually applies an effect onto a fit.
    Which causes modules to actually do useful(tm) things.
    They are typically generated by the ExpressionBuild class
    but nothing prevents a user from making some of his own and running them onto a fit
    """
    def __init__(self):
        self.type = None
        """
        Type of the instance, describes which modification should be applied onto targets.
        """
        self.location = None
        """
        The location of this expression.
        """

        self.filter = None
        """
        The filter of this expression, this can be a group or skillRequirement Id
        """

        self.operation = None
        """
        Which operation should be applied.
        Any other values will be ignored, causing the ExpressionInfo to do nothing
        """

        self.targetAttributeId = None
        """
        Which attribute will be affected by the operation on the target.
        This will be used as dictionary lookup key on all matched targets (if any)
        """

        self.sourceAttributeId = None
        """
        Which source attribute will be used as calculation base for the operation.
        This will be used as dictionary lookup key on the owner passed to the run method
        """

    def validate(self):
        # Usual assortment of checks, applicable to any info object
        if self.operation is None or self.targetAttributeId is None or \
        self.sourceAttributeId is None:
            return False
        # For direct assignments, we must ensure that we target item directly
        if self.type in (const.infoAddItmMod, const.infoRmItmMod):
            return self.location in const.locConvMap.values()
        # For location+group filters, check possible target location and presence of group specifier
        elif self.type in (const.infoAddLocGrpMod, const.infoRmLocGrpMod):
            return self.location in (const.locChar, const.locShip, const.locTgt) and self.filter is not None
        # For location, check possible target location
        elif self.type in (const.infoAddLocMod, const.infoRmLocMod):
            return self.target in (const.locChar, const.locShip, const.locTgt)
        # For location+skill requirement filters, check possible target location and presence of
        # skill requirement specifier
        elif self.type in (const.infoAddLocSrqMod, const.infoRmLocSrqMod):
            return self.location in (const.locChar, const.locShip, const.locTgt) and self.filter is not None
        # For owner+skill requirement filters, check if target is character and presence
        # of skill requirement specifier
        elif self.type in (const.infoAddOwnSrqMod, const.infoRmOwnSrqMod):
            return self.location is const.locChar and self.filter is not None
        # For direct gang modifications, target must be none (assumed it's ship)
        elif self.type in (const.infoAddGangItmMod, const.infoRmGangItmMod):
            return self.location is None
        # For skill requirement filtered gang ship items modification, target
        # must be skill specifier
        elif self.type in (const.infoAddGangSrqMod, const.infoRmGangSrqMod):
            return self.filter is not None
        # For group filtered gang ship items modification, target must be
        # group specifier
        elif self.type in (const.infoAddGangGrpMod, const.infoRmGangGrpMod):
            return self.filter is not None
        # For skill requirement filtered gang in-space items modification,
        # target must be skill specifier
        elif self.type in (const.infoAddGangOwnSrqMod, const.infoRmGangOwnSrqMod):
            return self.filter is not None
        # Mark all unknown for validator info types as invalid
        else:
            return False
